# Generated by Django 5.1.6 on 2025-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_twofactorcode_delete_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='TwoFactorCode',
        ),
    ]
